version: '2'
services:
  update-shipping:
    image: aux-shipping-web
    stdin_open: true
    tty: true
    volumes:
      - /opt/www-dev:/usr/share/nginx/html
    ports:
      - 5000:80
    environment:
      - SERVER_HOST=localhost
      - SERVER_PORT=80
      - SERVER_SSL_PORT=443
      - BACKEND_HOST=10.88.30.35
      - BACKEND_PORT=8080
      - GIT_PATH=http://temp:88888888@10.88.30.35:2000/snowfox/aux-shipping-web.git
